In [3]:
#Exp no:

In [4]:
#Aim:To Perform Basics of Data Frame

In [39]:
#Name:sanika vijay kale
#Roll no:23
#Sec:c
#Subject:ET 2

# Creating series

In [6]:
# Program for creating Series using series() method of Pandas Library

In [7]:
#Import Pandas library
import pandas as pd

In [8]:
#Creating Student Name List
Name=["Sanika","Sandesha","Apurva","priya","Shruti"]
Name

['Sanika', 'Sandesha', 'Apurva', 'priya', 'Shruti']

In [9]:
#Creating a Series 
Roll_list=pd.Series(Name,index=[1,2,3,4,5])
print(Roll_list)

1      Sanika
2    Sandesha
3      Apurva
4       priya
5      Shruti
dtype: object

# Creating Data Frame

In [10]:
#Import Pandas library
import pandas as pd

In [11]:
#Creating Data Frame
df=pd.DataFrame([[10,12,14,16],[11,18,15,21],[12,13,14,15]],
columns= ["BIA","DBMS","DSS","CAO"])

In [13]:
df

   BIA  DBMS  DSS  CAO
0   10    12   14   16
1   11    18   15   21
2   12    13   14   15

In [14]:
df.shape

(3, 4)

In [15]:
df.size

12

In [16]:
df.ndim

2

# Adding Record(Row)to the data frame

In [36]:
df2=pd.DataFrame([[5,6,7,8]],
columns= ["BIA","DBMS","DSS","CAO"])

In [38]:
df3=df.append(df2,ignore_index=True)

C:\Users\anike\AppData\Local\Temp/ipykernel_14652/2783945210.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df.append(df2,ignore_index=True)

In [26]:
df3

    BIA  DBMS  DSS  CAO   CD  DM
0  10.0    12   14   16  NaN  12
1  11.0    18   15   21  NaN  15
2  12.0    13   14   15  NaN  16
3   NaN     6    7    8  5.0  14

# Adding Attribute(coloums)name DM

In [23]:
df3["DM"]=[12,15,16,14]

In [24]:
df3

    BIA  DBMS  DSS  CAO   CD  DM
0  10.0    12   14   16  NaN  12
1  11.0    18   15   21  NaN  15
2  12.0    13   14   15  NaN  16
3   NaN     6    7    8  5.0  14

# Deleting Record Frome df3 dataframe

In [27]:
df4=df3.drop(index=[1])

In [28]:
df4

    BIA  DBMS  DSS  CAO   CD  DM
0  10.0    12   14   16  NaN  12
2  12.0    13   14   15  NaN  16
3   NaN     6    7    8  5.0  14

# Deleting Attribute (coloums)from df3 dataframe

In [29]:
df5=df3.drop(columns=["DM"])

In [30]:
df5

    BIA  DBMS  DSS  CAO   CD
0  10.0    12   14   16  NaN
1  11.0    18   15   21  NaN
2  12.0    13   14   15  NaN
3   NaN     6    7    8  5.0

In [31]:
#Finding mean of DSS 

print("Mean of DSS:", df5["DSS"].mean())

Mean of DSS: 12.5

In [32]:
#Finding median of DSS

print("Median of DSS:", df5["DSS"].median())

Median of DSS: 14.0

In [33]:
#Finding mode of DSS

print("Mode of DSS:", df5["DSS"].mode())

Mode of DSS: 0    14
Name: DSS, dtype: int64

In [34]:
#Finding max number of DSS

print("Max of DSS:", df5["DSS"].max())

Max of DSS: 15

In [35]:
#Finding Min number of DSS

print("Max of DSS:", df5["DSS"].min())

Max of DSS: 7